# blackbox-values.yaml
blackboxExporter:
  config:
    modules:
      http_2xx:
        prober: http
        timeout: 5s
        http:
          valid_status_codes: [200]
          method: GET
          preferred_ip_protocol: ip4

serviceMonitor:
  enabled: true
  defaults:
    labels:
      release: prometheus
    interval: 30s
  targets:
    - name: example-http
      url: http://127.0.0.1:8080
      interval: 30s
      module: http_2xx
