prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector: {}

    additionalScrapeConfigs:
      - job_name: 'blackbox'
        metrics_path: /probe
        params:
          module: [http_2xx]
        static_configs:
          - targets:
            - http://digitops-service-service.digitops.svc.cluster.local:80 # Target URL to probe
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            # Using the exact service name from kubectl describe output
            replacement: blackbox-exporter-prometheus-blackbox-exporter.monitoring.svc:9115
      - job_name: 'blackbox_exporter'  # collect blackbox exporter's operational metrics.
        static_configs:
          - targets: ['blackbox-exporter-prometheus-blackbox-exporter.monitoring.svc:9115']          

additionalPrometheusRulesMap:
  service-monitoring-rules:
    groups:
      - name: service.rules
        rules:
          - alert: ServiceNotResponding
            expr: |
              (probe_success{instance="digitops-service-service.digitops.svc.cluster.local"} == 0) or
              (probe_http_status_code{instance="digitops-service-service.digitops.svc.cluster.local"} > 0 
               and probe_http_status_code{instance="digitops-service-service.digitops.svc.cluster.local"} != 200)
            for: 5m
            labels:
              severity: critical
            annotations:
              summary: "Service is not responding with 200 HTTP code"
              description: "digitops-service has not responded with HTTP 200 for more than 5 minutes"            
