# prometheus-values.yaml
prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector: {}

    # Add blackbox scrape config
    additionalScrapeConfigs:
      - job_name: 'blackbox'
        metrics_path: /probe
        params:
          module: [http_2xx]
        static_configs:
          - targets:
            - http://www.google.com  # Replace with your service URL
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: blackbox-exporter:9115

    # Configure alert rules
    additionalPrometheusRulesMap:
      service-monitoring-rules:
        groups:
          - name: service.rules
            rules:
              - alert: ServiceNot200Response
                expr: |
                  probe_http_status_code{job="blackbox"} != 200
                  or absent(probe_http_status_code{job="blackbox"})
                for: 5m
                labels:
                  severity: critical
                  team: sre
                annotations:
                  summary: "Service not responding with HTTP 200"
                  description: "{{ $labels.instance }} has not responded with HTTP 200 for more than 5 minutes"
                  runbook_url: "https://wiki.example.com/runbook/service-outage"
