prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector: {}

    additionalScrapeConfigs:
      - job_name: 'blackbox'
        metrics_path: /probe
        params:
          module: [http_2xx]
        static_configs:
          - targets:
            - https://site.com/contact.html  # Target URL to probe
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            # Using the exact service name from kubectl describe output
            replacement: blackbox-exporter-prometheus-blackbox-exporter.monitoring.svc:9115

    additionalPrometheusRules:
      - name: blackbox-alert
        groups:
          - name: blackbox-alerts
            rules:
              - alert: ServiceDown
                expr: probe_http_status_code != 200
                for: 5m
                labels:
                  severity: critical
                annotations:
                  summary: "Service is down"
                  description: "The service has not responded with HTTP 200 for more than 5 minutes."

