prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector: {}

    additionalScrapeConfigs:
      - job_name: 'blackbox'
        metrics_path: /probe
        params:
          module: [http_2xx]
        static_configs:
          - targets:
            - http://digitops-service-service.digitops.svc.cluster.local:80 # Target URL to probe
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            # Using the exact service name from kubectl describe output
            replacement: blackbox-exporter-prometheus-blackbox-exporter.monitoring.svc:9115
      - job_name: 'blackbox_exporter'  # collect blackbox exporter's operational metrics.
        static_configs:
          - targets: ['blackbox-exporter-prometheus-blackbox-exporter.monitoring.svc:9115']          

additionalPrometheusRulesMap:
  service-monitoring-rules:
    groups:
      - name: service.rules
        rules:
          - alert: ServiceNotResponding
            expr: |
              rate(probe_http_status_code{job="blackbox"}[5m]) == 0
            for: 5m
            labels:
              severity: critical
            annotations:
              summary: "Service is consistently not responding with 200 HTTP code"
              description: "{{ $labels.instance }} has had no successful responses (HTTP 200) for more than 5 minutes while still being probed"            
