name: Deploy Monitoring Stack

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to Kubernetes
        run: |
          # Delete existing pods to force update
          kubectl delete namespace monitoring
      - name: Add Prometheus helm repo
        run: |
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo update
      - name: Deploy Blackbox Exporter
        run: |
          helm upgrade --install blackbox-exporter prometheus-community/prometheus-blackbox-exporter \
            --namespace monitoring \
            -f ./blackbox-exporter/blackbox-values.yaml \
            --wait
      - name: Deploy Prometheus
        run: |
          helm upgrade --install prometheus prometheus-community/kube-prometheus-stack \
            --namespace monitoring \
            -f ./prometheus/prometheus-values.yaml \
            --wait --create-namespace

      
